import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import Header from "@/components/header";
import {
  ClerkProvider
} from '@clerk/nextjs'

const inter = Inter({subsets: ["latin"]})
export const metadata: Metadata = {
  title: "Coachai - AI Career Coach",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
        <html lang="en" suppressHydrationWarning>
          <body
            className={`${inter.className}`}
          >
            <ThemeProvider
              attribute="class"
              defaultTheme="dark"
              enableSystem
              disableTransitionOnChange
            >
                {/* header */}
                <Header></Header>
                <main className="min-h-screen">
                  {children}
                </main>
                {/* footer */}
                  <footer className="bg-muted/50 py-12 ">
                    <div className="container mx-auto px-4 text-center text-grey-200">
                      <p className="">Mane by @nguyenthaisonny</p>
                    </div>
                  </footer>
              </ThemeProvider>
          </body>
        </html>
    </ClerkProvider>

  );
}
